# Generated by Django 5.0.6 on 2024-05-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInicio', '0002_estudiante_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='cedula',
            field=models.BigIntegerField(verbose_name='Numero de cedula'),
        ),
    ]
