# Generated by Django 5.0.6 on 2024-05-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInicio', '0003_alter_estudiante_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='cedula',
            field=models.BigIntegerField(default=0, verbose_name='Numero de cedula'),
        ),
    ]
